[SERVICE]
    # Smanjuje interval slanja podataka na 1 sekundu. Korisno za debagovanje.
    Flush        1
    # Nivo logovanja za sam Fluent Bit.
    Log_Level    info

[INPUT]
    # Koristimo zvanični 'docker' input plugin koji je specijalno napravljen za ovo.
    Name        docker
    # Dajemo tag svim logovima koji dolaze iz ovog inputa.
    Tag         docker.*

[OUTPUT]
    # Šaljemo podatke na Loki.
    Name          loki
    Match         *
    # Koristimo ime servisa iz docker-compose.yml.
    Host          loki
    Port          3100
    # Ključni deo: Pretvori 'container_name' koji je INPUT dodao u Loki labelu.
    Labels        job=$container_name
    # Šalje originalnu log poruku kao glavni sadržaj.
    Line_Format   json