[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name         docker
    Docker_Mode  true
    Tag          docker.*

[FILTER]
    Name         docker
    Match        docker.*
    Add          container_name ${CONTAINER_NAME}

[OUTPUT]
    Name         loki
    Match        *
    Host         loki
    Port         3100
    Labels       job=fluent-bit,container_name=$CONTAINER_NAME(container_name)
    Label_keys   container_name