[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    # Slušaj za dolazeće poruke preko fluentd protokola na portu 24224
    Name         forward
    Listen       0.0.0.0
    Port         24224

[FILTER]
    # Ovaj filter izvlači ime kontejnera iz taga koji smo definisali u docker-compose
    # Npr. iz taga "docker.tour-service-1" izvlači "tour-service-1"
    Name         rewrite_tag
    Match        docker.*
    Rule         $log "^.*$" $container_name true
    Emitter_Name re_emitted

[OUTPUT]
    # Šalji sve obrađene logove na Loki
    Name          loki
    Match         *
    Host          loki
    Port          3100
    # Koristi izvučeno ime kontejnera kao 'job' labelu
    Labels        job=$container_name
    Line_Format   json